### ISSUE TITLE
Using React hooks

### ISSUE THREAD

**Issue by coderacheal** [coderacheal/math-magicians#3]
Steps I followed to use react hooks in my functional components 

1. I imported the usestate function from react
2. I destructured my usesate array into my initial state and the function I will use to update my state
3. I then set my initial state to an object that contains my total, next, and operations property to null
4. Lastly I defined a function where I update my state

![image](https://user-images.githubusercontent.com/97846040/221364953-09896dd2-5d9a-4b04-8735-2ef9311fd1e8.png)

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🎉✔🍾**
Hello @coderacheal 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
